name: Task
description: Raise a non-code task
title: "[Task]: "
# type: Task
projects: ["4"]
body:
  - type: input
    id: short-description
    attributes:
      label: Description
      placeholder: ex. We need to connect this to a remote server for the leaderboard to work
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What are one or more acceptance criteria that would be used to verify this task is completed?
      placeholder: ex. We have setup an AWS server which can have applications deployed to it
    validations:
      required: true
  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Are there any prerequisites for completing this task?
      placeholder: ex. Challenge organiser has access to the AWS account and can create a server 
    validations:
      required: false
  - type: textarea
    id: blockers
    attributes:
      label: Known or potential blockers
      description: Are there any known or potential blockers to completing this task?
      placeholder: ex. We need to obtain funding to pay for the server costs
    validations:
      required: false
  - type: checkboxes
    id: project-admin
    attributes:
      label: Assign the relevant label(s) and, if known, Milestone to this task
      options:
        - label: I confirm I have assigned the relevant label(s) and, if known, Milestone to this task
          required: true
